version: "3.7"

services:
  hellofresh:
    image: hellofresh
    build: images/hellofresh
    command: ["./src/main.py"]
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./template:/template
